# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=48)),
                ('batchNo', models.TextField(max_length=50)),
                ('expiryDate', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('pricePerPiece', models.PositiveSmallIntegerField()),
                ('dateOfPurchase', models.DateField(default=django.utils.timezone.now)),
                ('pharmacy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
