# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0003_auto_20160803_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pricePerTablet',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='noOfTablets',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pack',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='No. of Tablets per Strip'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pricePerPiece',
            field=models.PositiveSmallIntegerField(verbose_name='Rate per Strip'),
        ),
    ]
