# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0004_auto_20160804_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='noOfTabletsSold',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiryDate',
            field=models.DateField(verbose_name='Expiry Date : yyyy-mm-dd format'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medicineName',
            field=models.CharField(max_length=48, verbose_name='Medicine Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pricePerTablet',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Enter the number of strips Purchased'),
        ),
    ]
