# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0006_auto_20160809_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDetails',
            new_name='PatientDetail',
        ),
    ]
