# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0007_auto_20160810_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='dicount',
            field=models.PositiveSmallIntegerField(choices=[(10, 10), (5, 5), (0, 0)], default='0', verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='post',
            name='noOfTabletsInStores',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='patientID',
            field=models.CharField(blank=True, max_length=50, verbose_name='Enter the Patient ID'),
        ),
    ]
