# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0008_auto_20160831_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='dicount',
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (5, 5), (10, 10)], default='0', verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='discountedPrice',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='bill',
            name='transactionCompleted',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
