# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0009_auto_20160905_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='medicineName',
        ),
        migrations.AddField(
            model_name='bill',
            name='medicineName',
            field=models.CharField(default='NA', max_length=48, verbose_name='Medicine Name'),
        ),
    ]
