# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0010_auto_20160905_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='batchNo',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
