# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0011_bill_batchno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='medicineName',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='patientID',
        ),
        migrations.AddField(
            model_name='bill',
            name='patientID',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
    ]
