# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0012_auto_20160905_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.PatientDetail'),
        ),
    ]
