# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0016_auto_20160924_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateOfPurchase',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Of Purchase'),
        ),
    ]
