# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0017_auto_20160925_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='patientID',
            field=models.CharField(max_length=50, verbose_name='Patient ID'),
        ),
    ]
