# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0018_auto_20160925_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='patientID',
            field=models.CharField(blank=True, max_length=50, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='patientName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='patientPhoneNo',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Phone Number'),
        ),
    ]
