# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0019_auto_20160925_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='expiryDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Enter the number odf Strips'),
        ),
    ]
