# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0021_auto_20161004_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='netPurchasePrice',
        ),
    ]
