# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0022_remove_post_netpurchaseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pricePerStrip',
            field=models.PositiveSmallIntegerField(verbose_name='Enter thetrial'),
        ),
    ]
