# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0023_auto_20161004_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pricePerStrip',
        ),
        migrations.AddField(
            model_name='post',
            name='pricePerPiece',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='mrp',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Maximum Retail Price'),
        ),
    ]
