# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0024_auto_20161004_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pricePerPiece',
            new_name='pricePerStrip',
        ),
    ]
