# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0030_auto_20161004_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnSalesBillNo', models.CharField(max_length=50)),
                ('returnSalesMedicineName', models.CharField(blank=True, default='NA', max_length=50)),
                ('returnSalesBatchNo', models.CharField(default='NA', max_length=50)),
                ('returnSalesBillDate', models.DateField(default=django.utils.timezone.now, verbose_name='Date Of Purchase')),
                ('returnSalesNoOfTablets', models.PositiveSmallIntegerField(default='0')),
                ('originalPricePerTablet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('originalDiscount', models.PositiveSmallIntegerField(verbose_name='Discount (%)')),
                ('returnSalesDiscountedPricePerTablet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('totalReturnAmount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='returnSales',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='returnbill',
            name='originalBillNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.Bill'),
        ),
    ]
