# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0032_auto_20161015_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='returnDiscountedPrice',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
    ]
