# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0033_bill_returndiscountedprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discountedPrice',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bill',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
    ]
