# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 16:20
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0035_auto_20161101_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='noOfTabletsToTrf',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='batchNo',
            field=models.CharField(max_length=50, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='post',
            name='freeArticles',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Free Sample (Strips/Bottle/pack)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medicineName',
            field=models.CharField(max_length=48, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='M.R.P.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pack',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='No. of tablets per strip/bottle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pricePerStrip',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per strip/piece'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Number of strips/pieces purchased'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sat',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (4, 4), (5, 5), (12, 12)], default='0', verbose_name='SAT (%)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vat',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (4, 4), (5, 5), (12, 12)], default='4', verbose_name='VAT (%)'),
        ),
    ]
